### ISSUE TITLE
配置disqus_shortname后无法正常加载disqus

### ISSUE THREAD

**Issue by kulley** [GallenHu/hexo-theme-Daily#5]
无论墙与被墙

**Comment by glenhooo** [comment]
看你的html文件里，并没有生成disqus评论相关的代码。
能否贴一下你的_config.yml文件内容？

**Comment by kulley** [comment]
```
# basic
title: Daily
subtitle: Minimalism, simplicity and refined details
favicon: /images/favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
logo: /images/logo.png

# disqus
disqus_shortname: kulley

highlight:
  enable: true
  line_number: true 
  auto_detect: true
  tab_replace: 4

# nav #
nav:
  home: .
  archives: archives
  about: about
  # rss: atom.xml

# hexo-renderer-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false

# Default post title
default_post_title: Untitled

# social
social:
  github: https://github.com/Kulley
  weibo: http://weibo.com
  mail: mailto:kiki10631@163.com
  # twitter: https://twitter.com/GallenHu

# widget
#   title: 标题
#   content: 内容
widget:
  title: 关于本站
  content: 我能写的只是随便写写，你若看到就随便看看
  #<ul><li><a href="https://github.com/GallenHu/hexo-theme-Daily">如何自定义这里的内容(配置教程)?</a></li></ul>

footer: Powered by <a href="https://hexo.io/" target="_blank">Hexo</a> with Theme <a href="https://github.com/GallenHu/hexo-theme-Daily" target="_blank">Daily</a>

```

**Comment by glenhooo** [comment]
你没有配置主题： `theme: Daily` ?

**Comment by kulley** [comment]
上面那个是 ~/blog/Daily/_config.yml
下面这个是 ~/blog/_config.yml
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kulley
subtitle:
description:
author: Shawn Kulley
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Daily

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  branch: master
  repo: git@github.com:kulley/kulley.github.io.git

```
