### ISSUE TITLE
请问如何创建nav-about？

### ISSUE THREAD

**Issue by lwdjumpman23** [GallenHu/hexo-theme-Daily#9]
请教如何创建nav里面的About目录？
是直接在public下新建About文件夹？还是用git创建？

谢谢。

**Comment by glenhooo** [comment]
源文件的路径是 `source/about/index.md` , 会生成出来 `public/about/index.html`
然后修改 `_config.yml` 配置：

```
nav:
  Home: .
  Archive: archives
  About: about
```

可以参考我的博客源代码： https://github.com/Hinpc/hexo-blog-generator
